name: Notion To Blog

on:
  issues:
    types: [opened]

jobs:
  notion-to-blog:
    if: ${{ github.event.issue.user.login == github.actor && contains(github.event.issue.title, 'notion-ci') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: false

    - uses: mohuishou/notion-blog-actions@main
      with:
        token: ${{ secrets.CHECKOUT_TOKEN }}
        notion_secret: ${{ secrets.NOTION_AUTH_TOKEN }}
        database_id: ${{ secrets.NOTION_DATABASE_ID }}
        # status_name: "status"
        # status_published: "已发布"
        # status_unpublish: "待发布"
        migrate_image: false
        output: "./source/_posts/notion/"
        access_key_id: false
        access_key_secret: false
        bucket: false
        area: false
        prefix: false



    # - name: "migrate image"
    #   uses: peiel/notion-blog-actions/migrate@main
    #   with:
    #     input: "./tmp/*.md"

    # - name: "cp md files"
    #   run: |
    #     cp -f ./tmp/*.md ./content/posts/
    #     rm -rf ./tmp
    - name: git setting
      run: |
        git config --global user.email "1@lailin.xyz"
        git config --global user.name "mohuishou"

    - name: update blog
      run: |
        git add source
        git commit -m "feat: auto update by notion sync"
        git push